### ISSUE TITLE
List supported/recommended driver/library for each programming language in README.md

### ISSUE THREAD

**Issue by kokizzu** [cloudamqp/lavinmq#359]

**Comment by jage** [comment]
There's a lot of programming languages out there, any special ones you're interested in?

**Comment by kokizzu** [comment]
Go :3

**Comment by dentarg** [comment]
Not sure the LavinMQ team can recommend a client for any given language, but we could list those we have experience with.

Re: Go, I found https://github.com/avelino/awesome-go#messaging that's seems to list a few different clients (and more).
