### ISSUE TITLE
Lavinmq UI issue disable consumers sorting ?

### ISSUE THREAD

**Issue by geminigeek** [cloudamqp/lavinmq#386]
hi,

last night i cancelled a different consumer  and realized only after few hours as the auto sorting of consumers list is really annoying , as i hover my mouse over cancel , the list must have sorted and i ended up clicking wrong consumer !!!

the issue is "the consumers table in UI must be sorted by a consumer tag ( alphabetically ) "  or any other stable identifier so it doesn't  sort at all or sort  in a predictable manner.

thanks

**Comment by carlhoerberg** [comment]
Fixed in #391

**Comment by geminigeek** [comment]
> Fixed in #391

hi,

i just tested this in "1.0.0-beta.5" , the issue is still there the consumers are constantly sorting in UI , with same prefetch count
made a video of same https://youtu.be/fvnkDbhgi54

**Comment by kickster97** [comment]
Hi, unfortunately this fix missed the release of beta.5 and was merged after. We will release beta.6 in the coming days, and then the fix will be live. Thank you for your patience :)

**Comment by dentarg** [comment]
#391 was included in `v1.0.0-beta.6`: https://github.com/cloudamqp/lavinmq/releases/tag/v1.0.0-beta.6
