### ISSUE TITLE
CI: replace use of `actions/create-release` in release workflow

### ISSUE THREAD

**Issue by dentarg** [cloudamqp/lavinmq#401]
Use of `actions/create-release@v1` generates warnings at https://github.com/cloudamqp/lavinmq/actions/runs/3378636620

However, https://github.com/actions/create-release has been archived and should be replaced with something else.

Our current usage:

https://github.com/cloudamqp/lavinmq/blob/22b17fdf240672caeb11c4b428f581cde56f5650/.github/workflows/release.yml#L28-L36

We can probably use the GitHub CLI already installed in Actions VMs: https://cli.github.com/manual/gh_release_create

**Comment by carlhoerberg** [comment]
Fixed in https://github.com/cloudamqp/lavinmq/commit/57b8c42bb3884a70f31e5011fa7ab54fb441c626
