### ISSUE TITLE
Error: undefined method 'host=' for AMQP::Client

### ISSUE THREAD

**Issue by dch** [cloudamqp/lavinmq#449]
during build of v1.0.0-beta.8 in a FreeBSD container without network access:

```
E: Error target lavinmqperf failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/lavinmqperf.cr:485:12

 485 | client.host = "127.0.#{Random.rand(UInt8)}.#{Random.rand(UInt8)}" if @random_localhost
              ^---
Error: undefined method 'host=' for AMQP::Client

*** Error code 1
```

I patched this out to get a successful build, but this shouldn't fail at build time?

**Comment by carlhoerberg** [comment]
Must be an old version of https://github.com/cloudamqp/amqp-client.cr you have installed. Did you do `shards install` before `shards build`? 

https://github.com/cloudamqp/amqp-client.cr/commit/3b9b2580bbfa77a6d487fc2728f0a399dd154e69#diff-f0b2418208bf1243f621da2a47fbcf4ca3c7e28020771bb60758a5f7bd0164a0R90
