### ISSUE TITLE
Definitions' `null` parsing error

### ISSUE THREAD

**Issue by iamolegga** [cloudamqp/lavinmq#455]
Don't know if this is an error of definitions export or import but when I'm exporting definitions each `bindings.N.arguments` is `null`. When I'm trying to import definitions again with the UI or ctl I got errors.

- For ctl it's `cast from Nil to Hash(K, V) failed`.
- For UI it's `Upload failed`.

When I replace `null`s with empty objects `{}` in JSON it works

**Comment by carlhoerberg** [comment]
Thank you for reporting! Will fix
