### ISSUE TITLE
How to run a multi-node cluster ?

### ISSUE THREAD

**Issue by izanagi1995** [cloudamqp/lavinmq#499]
Hi,

Great project! I read the documentation and found no way to run a multi-node cluster. Is it supported? If yes, how can I achieve that?

Thanks!

**Comment by kickster97** [comment]
Hi Nicolas, thanks for your question! 
Correct, LavinMQ does not support multi-node clustering but you have the option to set up a hot standby server that can take over. Mount a shared disk to two machines and point LavinMQ on the machines to the shared data disk the start both servers. One will be the leader and run, whilst the other will wait on a shared lock until the leader is offline for some reason (crash/fail/restart..) and then the hot standby will start and take over.
