### ISSUE TITLE
undefined reference to `copy_file_range'

### ISSUE THREAD

**Issue by lightgao** [cloudamqp/lavinmq#544]
I fail to compile lavinmq v1.1.5 with Crystal 1.8.2 on CentOS 7. any suggestion ?

----------------------------------------------------------------------------------------

[liang@MiWiFi-R1CM-srv lavinmq]$ crystal version
Crystal 1.8.2 [7aa5cdd86] (2023-05-09)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu

[liang@MiWiFi-R1CM-srv lavinmq]$ git status
HEAD detached at v1.1.5
nothing to commit, working tree clean

[liang@MiWiFi-R1CM-srv lavinmq]$ git clean -ffdx
Removing bin/
Removing lib/

[liang@MiWiFi-R1CM-srv lavinmq]$ shards build --release --production
Resolving dependencies
Fetching https://github.com/cloudamqp/amqp-client.cr.git
Fetching https://github.com/cloudamqp/amq-protocol.cr.git
Fetching https://github.com/tbrand/router.cr.git
Fetching https://github.com/84codes/systemd.cr.git
Fetching https://github.com/luislavena/radix.git
Installing amq-protocol (1.1.4)
Installing amqp-client (1.0.11)
Installing radix (0.4.1)
Installing router (0.2.8)
Installing systemd (2.0.0)
Building: lavinmq
Error target lavinmq failed to compile:
_main.o: In function `copy':
/home/liang/apps/lavinmq/lavinmq/src/stdlib/copy_file_range.cr:63: undefined reference to `copy_file_range'
_main.o: In function `copy_file_range':
/home/liang/apps/lavinmq/lavinmq/src/stdlib/copy_file_range.cr:51: undefined reference to `copy_file_range'
/home/liang/apps/lavinmq/lavinmq/src/stdlib/copy_file_range.cr:23: undefined reference to `copy_file_range'
/home/liang/apps/lavinmq/lavinmq/src/stdlib/copy_file_range.cr:37: undefined reference to `copy_file_range'
_main.o: In function `copy':
/home/liang/apps/lavinmq/lavinmq/src/stdlib/copy_file_range.cr:63: undefined reference to `copy_file_range'
_main.o:/home/liang/apps/lavinmq/lavinmq/src/stdlib/copy_file_range.cr:51: more undefined references to `copy_file_range' follow
collect2: error: ld returned 1 exit status
Error: execution of command failed with exit status 1: cc "${@}" -o /home/liang/apps/lavinmq/lavinmq/bin/lavinmq  -rdynamic -L/usr/lib64/crystal -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre2-8 -lm -lgc -lpthread -levent   -lrt -lpthread -ldl

----------------------------------------------------------------------------------------

**Comment by carlhoerberg** [comment]
Yes, too old kernel version, copy_file_range was introduced in 4.5. But
something like 5.19 is recommended.
https://man7.org/linux/man-pages/man2/copy_file_range.2.html#HISTORY

**Comment by lightgao** [comment]
Thanks, you are right. old kernel & glibc, will upgrade to centos stream 9.
