### ISSUE TITLE
Add golang example and client-lib recommendation

### ISSUE THREAD

**Issue by kokizzu** [cloudamqp/lavinmq#553]
currently in readme only few language, sample code section also the same
https://lavinmq.com/documentation/
![image](https://github.com/cloudamqp/lavinmq/assets/1061610/bf487273-9548-4022-995b-f3d492fcdf59)
https://github.com/cloudamqp/lavinmq#lavinmq-with-various-plattforms
![image](https://github.com/cloudamqp/lavinmq/assets/1061610/04a207e2-26e8-455a-afb9-fc50f8e03fa5)

**Comment by kickster97** [comment]
Hi, thanks for the input! Any specific language you are after?

**Comment by kokizzu** [comment]
Golang

**Comment by kickster97** [comment]
Alright, thanks! we are looking into it :)

**Comment by kickster97** [comment]
Hello! Now we have put together a Golang tutorial with a client library recommendation, find it [here](https://lavinmq.com/documentation/go-sample-code) :)
