### ISSUE TITLE
Benchmark against kafka/redpanda/blazingmq

### ISSUE THREAD

**Issue by kokizzu** [cloudamqp/lavinmq#554]
Currently no benchmark published for use cases like in https://bloomberg.github.io/blazingmq/docs/performance/benchmarks/ (clustered and non-clustered setup) or detailed single case like this: https://softwaremill.com/mqperf/

**Comment by kickster97** [comment]
Hi, we have some docs on out benchmarking tool `lavinmqperf` on the LavinMQ website. Take a look at https://lavinmq.com/documentation/lavinmqperf. 
We have also published an entry on the CloudAMQP blog, where we talk about throughput and latency for LavinMQ, found here: https://www.cloudamqp.com/blog/lavinmq-benchmarks.html
