### ISSUE TITLE
Unstable API result of /api/exchanges/<vhost>/<exchange>/bindings/source

### ISSUE THREAD

**Issue by oldium** [cloudamqp/lavinmq#568]
The `/api/exchanges/<vhost>/<exchange>/bindings/source` results (visible on `/exchange#vhost=<vhost>&name=<exchange>` UI path) are random and this is visible on every UI refresh. The shown bindings change position on every refresh. It looks like the API call result is unstable and I wonder how pagination could work in this case.

I tested this on LavinMQ 1.1.7 and 1.2.2.

**Comment by kickster97** [comment]
Hi, thanks for bringing light to this! Will take a look at it.
