### ISSUE TITLE
Looks like confirm_timeout is not taken into account

### ISSUE THREAD

**Issue by oleg-andreyev** [cloudamqp/lavinmq#582]
I've been benching lavinmq vs rabbitmq today (seeking for alternative)

Done simple command (script) in application that publishes 1_000_000 messages.

1. First running lavinmq that it was wow 5000/m with confirm_timeout
2. Running same on rabbitmq that it was only 200/m, which was like WAT?
3. Remove `confirm_timeout` and re-testing rabbitmq, got ~6000-6500/m
4. Re-testing lavinmq got ~same numbers.

So I assume that lavinmq does not take into account `confirm_timeout`

**Comment by carlhoerberg** [comment]
I assume you mean publish confirm? Can I see your script?

**Comment by oleg-andreyev** [comment]
> I assume you mean publish confirm? Can I see your script?
yes.

https://gist.github.com/oleg-andreyev/38ff297f37642b00b850fcff19a1f713
line 65-69 and 149 control confirmation

**Based on my results... it looks like some issue in application/vendor code and not related to LavinMQ.**
But the only difference is DSN to rabbitmq or lavinmq.

```
With confirmation (0s):
    PURE PHP
        RabbitMQ 1_000_000 163.89215898514 163.3683180809  165.52759408951
        LavinMQ  1_000_000 70.716361045837 68.114816904068 67.401754140854
    Symfony (0)
        RabbitMQ 1_000_000 200m/s ~ 5000   200m/s ~ 5000   200m/s ~ 5000
        LavinMQ  1_000_000 207.63020610809 205.57001304626 206.60138106346
----
Without confirmation:
    PURE PHP
        RabbitMQ 1_000_000  35.41846704483  51.28434491157 49.241211175919
        LavinMQ  1_000_000  32.523216962814 31.42186498642 31.210392951965
    Symfony
        RabbitMQ 1_000_000 155.68859887123 152.84669089317 153.45652699471
        LavinMQ  1_000_000 157.84439706802 160.40936112404 161.86608910561
```

The thing that bugs me (maybe it's not related to LavinMQ) is magnitude of difference.
W/O Confirmation PURE/Symfony are close or 2x.
W/ Confirmation PURE/Symfony are close or 2x but Symfony + Confirm is 10x diff.
