### ISSUE TITLE
Please enable build target Debian 12 (bookworm) in the packagecloud APT repository

### ISSUE THREAD

**Issue by nifr** [cloudamqp/lavinmq#596]
Hey lavinmq folks 👋 
we're totally amazed by `lavinmq` and have been using it with great joy during development.

Thanks for all the hard work you put into this project and for making it available to the public ❤️ 

As we're currently switching our development containers from Debian 11 (bullseye) to 12 (bookworm) we sadly realized that we can't use your packagecloud APT repository to install `lavinmq` at the moment.

Would it be possible to enable Debian bookworm as a target on packagecloud?

Thank you so much in advance and have a great day 😎 

Note: There is a dependency conflict for `libssl1.1` on `bookworm` if we attempt to use the `bullseye` apt repository instead.

### Details

**Background** Debian 12 (bookworm) was released on `2023-06-10`.

---

**Given** I want to install `lavinmq` via apt on Debian 12 (bullseye) and architecture `arm64`
**When** I follow the installation instructions in [README.md#debianubuntu](https://github.com/cloudamqp/lavinmq/blob/main/README.md#debianubuntu)
**And** I update the list of available packages with `apt-get update`
**Then** the command fails because of a missing `bookworm` release with the following error:

<details>
<summary>APT Error: [..] does not have a Release file</summary>

```
Ign:11 https://packagecloud.io/cloudamqp/lavinmq/debian bookworm InRelease
Err:12 https://packagecloud.io/cloudamqp/lavinmq/debian bookworm Release
  404  Not Found [IP: 54.183.173.4 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/cloudamqp/lavinmq/debian bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

</details>

---

**Given** I use the `bullseye` apt repository on packagecloud (instead of `bookworm`)
**When** I update the package list with `apt-get update`
**And** I try to install `lavinmq` with `apt-get install -y lavinmq`
**Then** the installation fails because of broken dependencies with the following error:

<details>
<summary>APT Error: Depends on libssl1.1</summary>

```
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) lavinmq:arm64 < none -> 1.2.5-1 @un puN Ib >
Broken lavinmq:arm64 Depends on libevent-2.1-7:arm64 < none | 2.1.12-stable-8 @un uH > (>= 2.1.8-stable)
  Considering libevent-2.1-7:arm64 0 as a solution to lavinmq:arm64 9999
  Re-Instated libevent-2.1-7:arm64
Broken lavinmq:arm64 Depends on libssl1.1:arm64 < none @un H > (>= 1.1.1)
Done
E: Unable to correct problems, you have held broken packages.
```

</details>

**Comment by dentarg** [comment]
@nifr can you try the package built we just built for Debian 12 in https://github.com/cloudamqp/lavinmq/pull/597? You can find it on https://github.com/cloudamqp/lavinmq/actions/runs/6864241004 under "Artifacts"

**Comment by dentarg** [comment]
Nice, I've tested (amd64) too. Thanks for the `gh run download` command, useful!

```shell
# outside docker
gh run download 6864241004 --repo cloudamqp/lavinmq --name deb-packages-debian-12 --dir .
docker run --rm -it -w /app -v $(pwd):/app -p 5673:5673 -p 15673:15673 debian:12.2 bash
# inside docker
apt-get update && apt-get install -y ./linux_amd64/lavinmq_1.2.5-9-g79b8b9e1-1_amd64.deb
mkdir data ; lavinmq -D ./data -p 5673 --http-port=15673 --guest-only-loopback=false
```

**Comment by dentarg** [comment]
Packages will be uploaded to Packagecloud on the next release, is that good enough for you @nifr?

Not sure how far of that is, maybe @kickster97 can comment on it

**Comment by dentarg** [comment]
Oh we actual upload HEAD builds to Packagecloud too, so there will be something there soon

**Comment by dentarg** [comment]
Thank you for the kind words :)

The head package builds are located at https://packagecloud.io/cloudamqp/lavinmq-head/ by the way (I noticed that that isn't (yet) mentioned in the README).

I'll close this issue out then :)
