### ISSUE TITLE
Add docker-compose.yml, entrypoint.sh with environment variables and a script to generate TLS files

### ISSUE THREAD

**Issue by brunneis** [cloudamqp/lavinmq#612]
Implemented @ https://github.com/cloudamqp/lavinmq/pull/503

- [`Dockerfile`] Define TLS ports using `EXPOSE` instruction
- [`Dockerfile`] Shift the default `lavinmq` arguments to the `CMD` instruction
- [`Dockerfile`] Specify `entrypoint.sh` in the `ENTRYPOINT` instruction
- [`entrypoint.sh`] Implement environment variables for all `lavinmq` argument options
- [`entrypoint.sh`] Give preference to environment variables over `CMD` / Docker command
- [`extras/generate-tls-files.sh`] Include a script for generating the key and certificate required for TLS configuration

**Comment by carlhoerberg** [comment]
See comments on #503
