### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by fedevilensky** [cloudamqp/lavinmq#625]
Don't really know where to post this, but on the [documentation page](https://lavinmq.com/documentation/getting-started) you have a typo in which you guys wrote `AMQP-0-1-9` instead of `AMQP-0-9-1`

![image](https://github.com/cloudamqp/lavinmq/assets/19208605/67e737f3-fdab-4492-873c-f54714f233d2)

**Comment by kickster97** [comment]
Hello! Thank you for catching this, just deployed a fix and should be live soon :)
