### ISSUE TITLE
Shovel reconnect not working properly

### ISSUE THREAD

**Issue by cachiama** [cloudamqp/lavinmq#665]
Hi,

We are running LavinMQ `1.2.10` in production workloads with a shovel having a reconnect delay of `5s` and Ack mode `On confirm`.

The shovel retry mechanism seems to be not fully working, let me explain.

- Shovel randomly stops working with error `CHANNEL_ERROR - Channel 1 not open (504)`
- The reconnect does actually attempt to reconnect, however it ends up getting the same error on every attempt.
```
25/04/2024, 11:19:16	error	shovel	
CHANNEL_ERROR - Channel 1 not open (504)
25/04/2024, 11:19:21	info	shovel	
started
25/04/2024, 11:19:21	error	shovel	
CHANNEL_ERROR - Channel 1 not open (504)
25/04/2024, 11:19:26	info	shovel	
started
25/04/2024, 11:19:26	error	shovel	
CHANNEL_ERROR - Channel 1 not open (504)
25/04/2024, 11:19:31	info	shovel	
started
25/04/2024, 11:19:31	error	shovel	
CHANNEL_ERROR - Channel 1 not open (504)
.....
```
- Tapping edit and save on the shovel in error status, successfully restarts the shovel.
```
25/04/2024, 11:19:53	info	client[vhost=/ address=127.0.0.1:40884 name=Shovel some-local-queue source]	
Connection established for user=user
```

Thank you.

**Comment by spuun** [comment]
Thanks for the report!

Are the shovel connecting to another cluster or is everything local?
Anything logged when it disconnects the first time?

**Comment by viktorerlingsson** [comment]
Thanks for the report @cachiama ! 

We've identified the issue and are working on a fix. It should be available early next week.

**Comment by cachiama** [comment]
That is awesome, looking forward to your release :) Thanks again!

**Comment by viktorerlingsson** [comment]
This bugfix has been released in https://github.com/cloudamqp/lavinmq/releases/tag/v1.2.11
