### ISSUE TITLE
Show information about unacked messages

### ISSUE THREAD

**Issue by viktorerlingsson** [cloudamqp/lavinmq#686]
Add views/API endpoints that shows information about unacked messages in a queue. See comment below for more information https://github.com/cloudamqp/lavinmq/issues/686#issuecomment-2135565645

**Comment by blj** [comment]
**Use Case Scenario: Displaying Unacked Messages in LavinMQ UI / API / Websocket**

**User Story:**
As a member of the operations team, I need to view details of messages currently being processed by consumers (in unacked state) in the LavinMQ UI. This information is crucial for tracking the progress of message processing and identifying potential bottlenecks.

**Primary Actor:**
Operations team member

**Preconditions:**
- The LavinMQ queue system is running.
- Messages are being consumed by various consumers.

**Main Flow:**
1. The operations team member accesses the LavinMQ UI / API / Websocket.
2. The UI displays a list of messages currently in the unacked state in a queue
3. For each unacked message, the UI shows:
   - Message ID
   - Timestamp when the message was consumed
   - Consumer ID

**Postconditions:**
- The user can see near real-time details of messages in the unacked state.
- The team member can use this information to monitor message processing and address any issues promptly.

**Benefits:**
- Provides visibility into message processing status.
- Helps in identifying and resolving potential bottlenecks.
- Enhances the ability to manage and optimize the queue system effectively.

**Comment by blj** [comment]
It is probably worth mentioning the whole is about observability of a message transitioning through different states. i.e. when the message got in to the queue, what is the priority, what is its current status etc. An API end point to get all messages in queue whether it is ack/un-acked. That will be great.
