### ISSUE TITLE
Clustering - add action for renaming replicated files

### ISSUE THREAD

**Issue by viktorerlingsson** [cloudamqp/lavinmq#806]
Add a RenameAction to clustering.

Needed for https://github.com/cloudamqp/lavinmq/pull/661

We probably need to add a more explicit way to select what action to be taken. 
Now it's determined by an Int64 that also holds the length of the content to sync: `delete` file if it's 0, `append` to file if it's negative and `add` file if it's positive. 

So maybe add an Int8 for action selection.

**Comment by carlhoerberg** [comment]
Why is it necessary? If you receive a file you already got, then store it to a temp file and then rename it back when you received the full file.

**Comment by carlhoerberg** [comment]
I would like to avoid it. Less data = less bandwidth and less cpu cycles for encoding/decoding. Would also break protocol compatibility.
