### ISSUE TITLE
Feature request: TTL for Exchange and Queues

### ISSUE THREAD

**Issue by thebestgin** [cloudamqp/lavinmq#814]
**Is your feature request related to a problem? Please describe**
I am always very frustrated when I see all the unnecessary exchanges and queues that are no longer needed. It is very tedious to filter them out and delete them via UI. AutoDelete is not an option because messages are lost in that case.

**Describe the solution you'd like**
I would find an AutoDelete very cool for time period-based inactive exchanges and queues.
So the exchange or queue has not been used for 30 days then deletion.
So a TTL for exchange and queue.
It is also a feature that I miss in the other MessageBrokers on the market.

**Describe alternatives you've considered**
Alternatively, I have to use TTL messages and implement the whole thing in a complex and roundabout way.
Another alternative are CronJobs that delete the exchanges and queues that are no longer used after this time.

**Comment by viktorerlingsson** [comment]
Hi @thebestgin 

You can already achieve this with queues by setting a TTL on the queue, or by setting a policy, see https://lavinmq.com/documentation/amqp-queues#temporary-queues

It can also be achieved for exchanges by using auto-delete exchanges. They are automatically deleted when the last binding is removed, see https://lavinmq.com/documentation/amqp-exchanges#auto-deleted-exchange. Using auto-delete exchanges together with temporary queues means the exchange is automatically deleted when the last queue that has a binding there is deleted.
