### ISSUE TITLE
 Sorting channels on unacked messages does not work as expected

### ISSUE THREAD

**Issue by kickster97** [cloudamqp/lavinmq#820]
**Describe the bug**
When trying to sort channels on unacked messages, it does not work (see image) 
<img width="1185" alt="image" src="https://github.com/user-attachments/assets/43af58a4-3b6b-41b9-af31-974ca6ca6858">

**Describe your setup**
Running LavinMQ locally, on macos

**How to reproduce**
set up a few queues, some with unacked messages and some without unacked messages, and try to sort them in the management interface on the channels page. 

**Expected behavior**
It should sort them in order depending on the arrow direction.

**Comment by mattkelly** [comment]
We're also seeing this: specifically that ordering does not work across pagination. It's a big blocker for effectively utilizing the LavinMQ UI for debug.

**Comment by kickster97** [comment]
Alright, thanks for the boost! I will try to put some time into solving this issue this week.
