### ISSUE TITLE
Don't unmap message segments before last consumer is done

### ISSUE THREAD

**Issue by snichme** [cloudamqp/lavinmq#825]
**Describe the bug**

We have a bug (hard to trigger) that we may unmap message segments before the last consumer deliver loop has finish writing to the socket, causing a segmentation fault.

We should rethink when we do the unmap. Maybe a fiber waiting for all deliver loops to be done (using a WaitGroup).

**Comment by snichme** [comment]
@spuun solved by https://github.com/cloudamqp/lavinmq/pull/850 right?

**Comment by spuun** [comment]
Yes, #850 solved this.
